name: faber_kku_plant
description: "- For your own gardening."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.2
  universal_html: ^2.0.8
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.2.0
  table_calendar: ^3.0.9
  url_launcher: ^6.1.5

  image: ^4.1.7
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
